# Generated by Django 6.0.3 on 2026-09-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomQuotationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desired_route",
                    models.TextField(help_text="Describe your desired route/locations"),
                ),
                ("adults", models.IntegerField(default=1)),
                ("children", models.IntegerField(default=0)),
                ("infants", models.IntegerField(default=0)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("travel_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special requirements, dietary needs, etc.",
                    ),
                ),
                (
                    "admin_quoted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "generated_itinerary",
                    models.TextField(
                        blank=True, help_text="Admin generated day-by-day itinerary"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("QUOTED", "Quoted"),
                            ("ACCEPTED", "Accepted by User"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_name", models.CharField(max_length=255)),
                ("total_days", models.IntegerField(default=0)),
                (
                    "selected_hotel_category",
                    models.CharField(
                        choices=[
                            ("BUDGET", "Budget"),
                            ("THREE_STAR", "3 Star"),
                            ("FOUR_STAR", "4 Star"),
                            ("LUXURY", "Luxury"),
                        ],
                        default="BUDGET",
                        max_length=15,
                    ),
                ),
                ("adults", models.IntegerField(default=1)),
                ("children", models.IntegerField(default=0)),
                ("infants", models.IntegerField(default=0)),
                (
                    "total_calculated_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SAVED", "Saved"),
                            ("CONVERTED", "Converted to Booking"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_activities",
                    models.ManyToManyField(blank=True, to="destinations.activity"),
                ),
                (
                    "selected_transportation",
                    models.ManyToManyField(
                        blank=True, to="destinations.transportation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomTripDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("days_stay", models.IntegerField(default=2)),
                (
                    "custom_trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_destinations",
                        to="custom_trips.customtrip",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
