# Generated by Django 6.0.3 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtrip",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE", "Single"),
                    ("COUPLE", "Couple"),
                    ("FAMILY", "Family"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customtrip",
            name="selected_hotel_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUDGET", "Budget"),
                    ("THREE_STAR", "3 Star"),
                    ("FOUR_STAR", "4 Star"),
                    ("LUXURY", "Luxury"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
