# Generated by Django 6.0.3 on 2026-09-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredefinedPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Person"),
                            ("COUPLE", "Couple"),
                            ("FAMILY", "Family"),
                        ],
                        default="SINGLE",
                        max_length=10,
                    ),
                ),
                ("base_days", models.IntegerField(default=3)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_day_extra_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "highlights",
                    models.TextField(
                        blank=True, help_text="Comma separated highlights"
                    ),
                ),
                (
                    "inclusions",
                    models.TextField(blank=True, help_text="What is included"),
                ),
                (
                    "exclusions",
                    models.TextField(blank=True, help_text="What is excluded"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                ("is_popular", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="destinations.destination",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="destinations.hotel",
                    ),
                ),
                (
                    "included_activities",
                    models.ManyToManyField(
                        blank=True, related_name="packages", to="destinations.activity"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
