# Generated by Django 6.0.3 on 2026-09-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("INSIDE_COUNTRY", "Inside Country"),
                            ("OUTSIDE_COUNTRY", "Outside Country"),
                        ],
                        default="INSIDE_COUNTRY",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="destinations/main/"
                    ),
                ),
                ("rules_regulations", models.TextField(blank=True)),
                ("best_season", models.CharField(blank=True, max_length=200)),
                (
                    "base_visit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "adult_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "child_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="activities/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DestinationGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="destinations/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUDGET", "Budget"),
                            ("THREE_STAR", "3 Star"),
                            ("FOUR_STAR", "4 Star"),
                            ("LUXURY", "Luxury"),
                        ],
                        default="BUDGET",
                        max_length=15,
                    ),
                ),
                (
                    "per_night_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "room_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated: Single,Double,Deluxe",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transportation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_origin", models.CharField(max_length=200)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BUS", "Tourist Bus"),
                            ("CAR", "Private Car"),
                            ("JEEP", "Jeep"),
                            ("FLIGHT", "Flight"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "per_person_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_vehicle_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=2, max_digits=4),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transportations",
                        to="destinations.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "destination")},
            },
        ),
    ]
