# Generated by Django 6.0.3 on 2026-09-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Payment"),
                            ("PARTIAL_30", "30% Partial"),
                        ],
                        default="FULL",
                        max_length=15,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("ESEWA", "eSewa"),
                            ("KHALTI", "Khalti"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        blank=True,
                        help_text="Gateway/Reference ID from payment",
                        max_length=100,
                    ),
                ),
                (
                    "payment_receipt",
                    models.ImageField(
                        blank=True,
                        help_text="Upload scanned deposit voucher or screenshot",
                        null=True,
                        upload_to="payments/receipts/",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("depositor_name", models.CharField(blank=True, max_length=100)),
                ("deposit_date", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("admin_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tickets.standaloneticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
