# Generated by Django 6.0.3 on 2026-09-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("BUS", "Bus"), ("FLIGHT", "Flight")], max_length=10
                    ),
                ),
                ("operator_name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=150)),
                ("destination", models.CharField(max_length=150)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("available_seats", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "days_of_week",
                    models.CharField(
                        default="Mon,Tue,Wed,Thu,Fri,Sat,Sun",
                        help_text="Comma separated days: Mon,Tue,Wed,Thu,Fri,Sat,Sun",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandaloneTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("BUS", "Bus"), ("FLIGHT", "Flight")],
                        default="BUS",
                        max_length=10,
                    ),
                ),
                ("operator_name", models.CharField(blank=True, max_length=100)),
                ("origin", models.CharField(max_length=150)),
                ("destination", models.CharField(max_length=150)),
                ("travel_date", models.DateField()),
                ("travel_time", models.TimeField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("passenger_count", models.IntegerField(default=1)),
                ("passenger_names", models.TextField(blank=True)),
                ("seat_numbers", models.CharField(blank=True, max_length=100)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "ticket_document",
                    models.FileField(
                        blank=True,
                        help_text="PDF ticket file",
                        null=True,
                        upload_to="tickets/documents/",
                    ),
                ),
                ("payment_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
